### ISSUE TITLE
model_best.pth missing?

### ISSUE THREAD

**Issue by cga-cmu** [lijenchang/Mask2Hand#3]
To run demo.py I seem to need the file model_best.pth in the directory checkpoint/

Traceback (most recent call last):
  File "demo.py", line 218, in <module>
    test()
  File "demo.py", line 206, in test
    checkpoint = torch.load(os.path.join(PATH, checkpoint_dir, 'model_best.pth'), map_location = device)
  File "/home/cga/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/cga/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/cga/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/model_best.pth'

I got around this problem by using model_pretrained.pth
(pytorch3d) cga@baxter:checkpoint$ ln -s model_pretrained.pth model_best.pth

**Comment by lijenchang** [comment]
It should indeed refer to `model_pretrained.pth`, not `model_best.pth`. I’ve corrected the typo in the latest commit.
